spring:
  application:
    name: OAuth2-keycloak

  datasource:
      password: Amine1998@@
      username: root
      url: jdbc:mysql://localhost:3303/Keycloak
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      database: mysql
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          jdbc.batch_size: 30
          order_inserts: true
          jdbc.time_zone: UTC
          #        dialect: org.hibernate.dialect.MySQLDialect
          types.print.banner: false
          format_sql: true

  server:
    port: 8080

  security:
    oauth2:


      client:
        registration:
          keycloak:
            client-id: alibou-rest-api
            client-secret: zgNjjHgSC1aa8BLBsEBmnnp8tzKQ5UvZ
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: http://localhost:1111/auth/realms/Alibou/protocol/openid-connect/auth
            token-uri: http://localhost:1111/auth/realms/Alibou/protocol/openid-connect/token
            user-info-uri: http://localhost:1111/auth/realms/Alibou/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:1111/auth/realms/Alibou/protocol/openid-connect/certs
            issuer-uri: http://localhost:1111/realms/Alibou



logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: DEBUG

